[package]
name = "hatter"
version = "0.0.0-dev"
authors = ["chris west <c@xvxx.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
